In [8]:
import torch
import numpy as np

In [9]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
y = torch.from_numpy(x)

In [11]:
y

tensor([[1, 2],
        [3, 4]])

In [12]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [13]:
import torchvision

In [14]:
#Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [15]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

In [16]:
# Compute gradients.
y.backward()

In [17]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [18]:
import torch.nn as nn
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.3883,  0.4816, -0.4607],
        [ 0.2444,  0.5418,  0.0979]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2140,  0.3780], requires_grad=True)


In [19]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [20]:
# Forward pass.
pred = linear(x)

In [21]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.033578872680664


In [22]:
# Backward pass.
loss.backward()

In [23]:
# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[ 0.1225,  0.4134, -0.2993],
        [ 0.4251,  0.2695,  0.4152]])
dL/db:  tensor([0.1860, 0.2253])


In [24]:
# 1-step gradient descent.
optimizer.step()


In [25]:
# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.025748372077942


In [26]:
pred

tensor([[-1.0749, -0.1701],
        [-0.1130,  0.3105],
        [-0.4521, -0.3714],
        [ 0.2397,  0.0763],
        [ 0.3183,  1.2312],
        [-0.7122,  0.2241],
        [ 0.4968,  0.9945],
        [ 0.2600,  0.6751],
        [-1.1871,  0.5439],
        [ 0.5055,  1.1275]], grad_fn=<AddmmBackward>)

In [34]:
import torchvision