In [35]:
import torch
import numpy as np

In [7]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [8]:
y = torch.from_numpy(x)

In [9]:
y

tensor([[1, 2],
        [3, 4]])

In [11]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [17]:
import torchvision

In [19]:
#Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [20]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

In [21]:
# Compute gradients.
y.backward()

In [22]:
# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [24]:
import torch.nn as nn
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.2849, -0.0903,  0.0264],
        [ 0.4891,  0.0214,  0.5614]], requires_grad=True)
b:  Parameter containing:
tensor([-0.2686,  0.2436], requires_grad=True)


In [25]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [26]:
# Forward pass.
pred = linear(x)

In [27]:
# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.2617533206939697


In [28]:
# Backward pass.
loss.backward()

In [29]:
# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.2726,  0.0289,  0.3314],
        [-0.1824, -0.5296,  0.8146]])
dL/db:  tensor([-0.2916,  0.4857])


In [30]:
# 1-step gradient descent.
optimizer.step()


In [31]:
# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.2470248937606812


In [32]:
pred

tensor([[-0.0301,  1.1668],
        [-0.2245,  0.1392],
        [-0.5175,  0.0503],
        [-0.2654, -0.2776],
        [-0.0319,  0.1128],
        [-0.5617,  0.5518],
        [ 0.0893, -0.1910],
        [-0.0838,  0.9773],
        [-0.4532,  1.1025],
        [-0.1993, -0.2553]], grad_fn=<AddmmBackward>)

In [34]:
import torchvision