# Numpy

For performance reasons, use numpy 


## Lists


In [1]:
import numpy as np
my_arr = np.arange(10000)   ### Numpy array
my_list = list(range(10000))   ###  Python array
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 74 µs, sys: 23 µs, total: 97 µs
Wall time: 98.9 µs
CPU times: user 3.15 ms, sys: 0 ns, total: 3.15 ms
Wall time: 3.43 ms


## Arrays

In [2]:
np.random.rand(3, 4) * 1000

array([[747.73429432, 338.77832372, 342.00220259,  75.97971834],
       [576.69427427, 383.59812953, 676.31914504, 272.94700493],
       [189.47391896, 331.92361937, 181.59941244, 623.45229199]])

In [3]:
data = np.random.randn(2, 3)
data

array([[ 0.11877949, -1.98466894, -0.70022419],
       [ 0.63162756, -0.15524045, -0.21537837]])

### Working with Numpy Arrays

In [4]:
data * 10

array([[  1.18779485, -19.8466894 ,  -7.00224188],
       [  6.31627556,  -1.55240447,  -2.15378373]])

In [5]:
data + data

array([[ 0.23755897, -3.96933788, -1.40044838],
       [ 1.26325511, -0.31048089, -0.43075675]])