# Numpy

## Numpy Arrays

In [2]:
np.random.rand(3, 4) * 1000

array([[929.62, 316.38, 183.92, 204.56],
       [567.73, 595.54, 964.51, 653.18],
       [748.91, 653.57, 747.71, 961.31]])

In [3]:
import numpy as np
my_arr = np.arange(10000)   ### Numpy array
my_list = list(range(10000))   ###  Python array
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 290 µs, sys: 213 µs, total: 503 µs
Wall time: 3.8 ms
CPU times: user 4.24 ms, sys: 147 µs, total: 4.39 ms
Wall time: 4.6 ms


In [4]:
data = np.random.randn(2, 3)
data

array([[ 1.01, -1.3 ,  0.27],
       [ 0.23,  1.35,  0.89]])

In [5]:
data * 10

array([[ 10.07, -12.96,   2.75],
       [  2.29,  13.53,   8.86]])

In [6]:
data + data

array([[ 2.01, -2.59,  0.55],
       [ 0.46,  2.71,  1.77]])